# Generated by Django 4.0.4 on 2022-05-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ClienteID', models.AutoField(primary_key=True, serialize=False)),
                ('ClienteNombre', models.CharField(max_length=50)),
                ('ClienteApellido', models.CharField(max_length=50)),
            ],
        ),
    ]
